// @ts-nocheck
import { NextRequest, NextResponse } from "next/server";
import { createServer, createAdminClient } from "@/lib/supabase/server";
import { addCreditsFromPayment } from "@/lib/credits/transactions";

/**
 * POST /api/sync-payment
  * Body: { paymentId?: string } - optional internal DB payment ID
   *
    * Finds all pending payments for the user and tries to sync them with MP.
     * If paymentId is provided, only syncs that specific payment.
      * Idempotent - safe to call multiple times.
       */
       export async function POST(req: NextRequest) {
         const supabase = createServer();
           const { data: auth } = await supabase.auth.getUser();
             if (!auth.user) {
                 return NextResponse.json({ error: "unauthorized" }, { status: 401 });
                   }

                     const admin = createAdminClient();
                       const accessToken = process.env.MERCADO_PAGO_ACCESS_TOKEN;
                         if (!accessToken) {
                             return NextResponse.json({ error: "mp_token_missing" }, { status: 500 });
                               }

                                 let paymentId: string | null = null;
                                   try {
                                       const body = await req.json();
                                           paymentId = body.paymentId ?? null;
                                             } catch {
                                                 // no body is fine
                                                   }

                                                     // Fetch pending payments for this user
                                                       let query = admin.from("payments").select("*").eq("user_id", auth.user.id).eq("status", "pending");
                                                         if (paymentId) {
                                                             query = query.eq("id", paymentId);
                                                               }
                                                                 const { data: pendingPayments } = await query.order("created_at", { ascending: false }).limit(10);

                                                                   if (!pendingPayments || pendingPayments.length === 0) {
                                                                       // No pending payments - return current credits
                                                                           const { data: profile } = await admin.from("profiles").select("credits_available").eq("id", auth.user.id).single();
                                                                               return NextResponse.json({ status: "no_pending", credited: false, credits: profile?.credits_available ?? 0 });
                                                                                 }

                                                                                   let creditedCount = 0;
                                                                                     let lastCredits = 0;

                                                                                       for (const payment of pendingPayments) {
                                                                                           try {
                                                                                                 let mpPayment: any = null;

                                                                                                       // Strategy 1: fetch by mp_payment_id if we have it
                                                                                                             if (payment.mp_payment_id) {
                                                                                                                     try {
                                                                                                                               const r = await fetch(`https://api.mercadopago.com/v1/payments/${payment.mp_payment_id}`, {
                                                                                                                                           headers: { Authorization: "Bearer " + accessToken },
                                                                                                                                                     });
                                                                                                                                                               if (r.ok) mpPayment = await r.json();
                                                                                                                                                                       } catch {
                                                                                                                                                                                 // fall through to strategy 2
                                                                                                                                                                                         }
                                                                                                                                                                                               }

                                                                                                                                                                                                     // Strategy 2: search by external_reference (= internal payment.id)
                                                                                                                                                                                                           if (!mpPayment && payment.mp_preference_id) {
                                                                                                                                                                                                                   try {
                                                                                                                                                                                                                             const r = await fetch(
                                                                                                                                                                                                                                         `https://api.mercadopago.com/v1/payments/search?external_reference=${payment.id}&sort=date_created&criteria=desc&range=date_created&begin_date=NOW-30DAYS&end_date=NOW`,
                                                                                                                                                                                                                                                     { headers: { Authorization: "Bearer " + accessToken } }
                                                                                                                                                                                                                                                               );
                                                                                                                                                                                                                                                                         if (r.ok) {
                                                                                                                                                                                                                                                                                     const data = await r.json();
                                                                                                                                                                                                                                                                                                 if (data.results && data.results.length > 0) {
                                                                                                                                                                                                                                                                                                               mpPayment = data.results[0];
                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                             } catch {
                                                                                                                                                                                                                                                                                                                                                       // continue
                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                           if (!mpPayment) continue;

                                                                                                                                                                                                                                                                                                                                                                                 // Map MP status to internal status
                                                                                                                                                                                                                                                                                                                                                                                       const mpStatus = mpPayment.status; // approved, pending, rejected, cancelled, etc.
                                                                                                                                                                                                                                                                                                                                                                                             const internalStatus = mpStatus === "approved" ? "approved" : mpStatus === "pending" || mpStatus === "in_process" || mpStatus === "authorized" ? "pending" : "rejected";

                                                                                                                                                                                                                                                                                                                                                                                                   // Update payment record
                                                                                                                                                                                                                                                                                                                                                                                                         await admin.from("payments").update({
                                                                                                                                                                                                                                                                                                                                                                                                                 mp_payment_id: String(mpPayment.id),
                                                                                                                                                                                                                                                                                                                                                                                                                         mp_status: mpStatus,
                                                                                                                                                                                                                                                                                                                                                                                                                                 status: internalStatus,
                                                                                                                                                                                                                                                                                                                                                                                                                                         payment_method: mpPayment.payment_method_id ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                 raw_payload: mpPayment,
                                                                                                                                                                                                                                                                                                                                                                                                                                                       }).eq("id", payment.id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Credit if approved and not yet credited
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (internalStatus === "approved" && !payment.credited_at) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           await addCreditsFromPayment({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     userId: payment.user_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               amount: payment.credits_purchased,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         paymentId: payment.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   description: "Compra de " + payment.package_name + " (" + payment.credits_purchased + " creditos)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   creditedCount++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   console.error("[sync-payment] error processing payment", payment.id, err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Return updated credit balance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const { data: profile } = await admin.from("profiles").select("credits_available").eq("id", auth.user.id).single();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               lastCredits = profile?.credits_available ?? 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return NextResponse.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     status: creditedCount > 0 ? "approved" : "pending",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         credited: creditedCount > 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             creditedCount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 credits: lastCredits,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }