// @ts-nocheck
import { NextRequest, NextResponse } from "next/server";
import { createServer, createAdminClient } from "@/lib/supabase/server";
import { getMpPayment, mapMpStatus } from "@/lib/payments/mercadopago";
import { addCreditsFromPayment } from "@/lib/credits/transactions";

/**
 * POST /api/sync-payment
  * Body: { paymentId: string } - internal DB payment ID
   *
    * Called by the frontend after user returns from MP checkout.
     * Fetches the latest payment status from MP and credits the user if approved.
      * Idempotent - safe to call multiple times.
       */
       export async function POST(req: NextRequest) {
         const supabase = createServer();
           const { data: auth } = await supabase.auth.getUser();
             if (!auth.user) {
                 return NextResponse.json({ error: "unauthorized" }, { status: 401 });
                   }

                     let paymentId: string;
                       try {
                           const body = await req.json();
                               paymentId = body.paymentId;
                                 } catch {
                                     return NextResponse.json({ error: "invalid_body" }, { status: 400 });
                                       }

                                         if (!paymentId) {
                                             return NextResponse.json({ error: "missing_paymentId" }, { status: 400 });
                                               }

                                                 const admin = createAdminClient();

                                                   // Find the payment in DB - must belong to this user
                                                     const { data: payment, error: findErr } = await admin
                                                         .from("payments")
                                                             .select("*")
                                                                 .eq("id", paymentId)
                                                                     .eq("user_id", auth.user.id)
                                                                         .single();

                                                                           if (findErr || !payment) {
                                                                               return NextResponse.json({ error: "payment_not_found" }, { status: 404 });
                                                                                 }

                                                                                   // Already credited - return current credits
                                                                                     if (payment.status === "approved" && payment.credited_at) {
                                                                                         const { data: profile } = await admin
                                                                                               .from("profiles")
                                                                                                     .select("credits_available")
                                                                                                           .eq("id", auth.user.id)
                                                                                                                 .single();
                                                                                                                     return NextResponse.json({
                                                                                                                           status: "approved",
                                                                                                                                 credited: true,
                                                                                                                                       credits: profile?.credits_available ?? 0,
                                                                                                                                           });
                                                                                                                                             }

                                                                                                                                               // If we have an MP payment ID, fetch from MP directly
                                                                                                                                                 if (payment.mp_payment_id) {
                                                                                                                                                     try {
                                                                                                                                                           const mp = await getMpPayment(payment.mp_payment_id);
                                                                                                                                                                 const internalStatus = mapMpStatus(mp.status);

                                                                                                                                                                       await admin
                                                                                                                                                                               .from("payments")
                                                                                                                                                                                       .update({
                                                                                                                                                                                                 mp_status: mp.status,
                                                                                                                                                                                                           status: internalStatus,
                                                                                                                                                                                                                     payment_method: mp.payment_method_id ?? null,
                                                                                                                                                                                                                               raw_payload: mp,
                                                                                                                                                                                                                                       })
                                                                                                                                                                                                                                               .eq("id", payment.id);

                                                                                                                                                                                                                                                     if (internalStatus === "approved" && !payment.credited_at) {
                                                                                                                                                                                                                                                             await addCreditsFromPayment({
                                                                                                                                                                                                                                                                       userId: payment.user_id,
                                                                                                                                                                                                                                                                                 amount: payment.credits_purchased,
                                                                                                                                                                                                                                                                                           paymentId: payment.id,
                                                                                                                                                                                                                                                                                                     description: "Compra de " + payment.package_name + " (" + payment.credits_purchased + " creditos)",
                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                     await admin
                                                                                                                                                                                                                                                                                                                               .from("payments")
                                                                                                                                                                                                                                                                                                                                         .update({ credited_at: new Date().toISOString() })
                                                                                                                                                                                                                                                                                                                                                   .eq("id", payment.id);
                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                               const { data: profile } = await admin
                                                                                                                                                                                                                                                                                                                                                                       .from("profiles")
                                                                                                                                                                                                                                                                                                                                                                               .select("credits_available")
                                                                                                                                                                                                                                                                                                                                                                                       .eq("id", auth.user.id)
                                                                                                                                                                                                                                                                                                                                                                                               .single();

                                                                                                                                                                                                                                                                                                                                                                                                     return NextResponse.json({
                                                                                                                                                                                                                                                                                                                                                                                                             status: internalStatus,
                                                                                                                                                                                                                                                                                                                                                                                                                     mpStatus: mp.status,
                                                                                                                                                                                                                                                                                                                                                                                                                             credited: internalStatus === "approved",
                                                                                                                                                                                                                                                                                                                                                                                                                                     credits: profile?.credits_available ?? 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                                                                                                               } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                     console.error("[sync-payment] MP fetch error", err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Fall through to search by preference
                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // If we have a preference ID but no payment ID yet, search MP by external_reference
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (payment.mp_preference_id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const accessToken = process.env.MP_ACCESS_TOKEN;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!accessToken) throw new Error("MP_ACCESS_TOKEN not set");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const searchResp = await fetch(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "https://api.mercadopago.com/v1/payments/search?external_reference=" + payment.id + "&sort=date_created&criteria=desc&range=date_created&begin_date=NOW-7DAYS&end_date=NOW",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           { headers: { Authorization: "Bearer " + accessToken } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const searchData = await searchResp.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const results = searchData?.results;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (results && results.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const mpPayment = results[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const internalStatus = mapMpStatus(mpPayment.status);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           await admin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     .from("payments")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               .update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           mp_payment_id: String(mpPayment.id),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       mp_status: mpPayment.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   status: internalStatus,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               payment_method: mpPayment.payment_method_id ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           raw_payload: mpPayment,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               .eq("id", payment.id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (internalStatus === "approved" && !payment.credited_at) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 await addCreditsFromPayment({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             userId: payment.user_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         amount: payment.credits_purchased,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     paymentId: payment.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 description: "Compra de " + payment.package_name + " (" + payment.credits_purchased + " creditos)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     await admin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .from("payments")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             .update({ credited_at: new Date().toISOString() })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         .eq("id", payment.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const { data: profile } = await admin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   .from("profiles")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             .select("credits_available")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       .eq("id", auth.user.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .single();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return NextResponse.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   status: internalStatus,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             mpStatus: mpPayment.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       credited: internalStatus === "approved",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 credits: profile?.credits_available ?? 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         console.error("[sync-payment] search error", err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Cannot determine status yet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const { data: profile } = await admin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       .from("profiles")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           .select("credits_available")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               .eq("id", auth.user.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   .single();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return NextResponse.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         status: payment.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             credited: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 credits: profile?.credits_available ?? 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }